import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const require = createRequire('/Users/john/.cache/piprail-video-tools/');
const { chromium } = require('playwright-core');
const BIN = process.env.HOME + "/Library/Caches/ms-playwright/chromium-1223/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
const b = await chromium.launch({ executablePath: BIN, headless: true, args:['--force-color-profile=srgb'] });
const p = await b.newPage({ viewport:{width:1600,height:900}, deviceScaleFactor:2 });
await p.goto(pathToFileURL('/Users/john/Sites/piprail/.claude/skills/site-design/design/video/card.html').href, { waitUntil:'load' });
await p.evaluate(()=>window.__ready).catch(()=>{});
await p.waitForTimeout(400);
await p.screenshot({ path: '/Users/john/Sites/piprail/piprail-sui-card.png' });
await b.close();
console.log('piprail-sui-card.png written (3200x1800)');
